export const ASSETS = {
  LOGO: "/assets/logo.png",
  PROFILE: "/assets/profile.jpg",
  MAC_ICON: "/assets/mac.svg",
  DOODLE: "/assets/doodle.png",
  SKILL_IMG: "/assets/skillImg.svg",
  CCI: "/assets/cci.png",
  FFSC: "/assets/ffsc.png",
  ART: {
    COFFEE_SHOP: "/assets/coffee_shop.png",
    POSTER_COFFEE: "/assets/poster_coffee.png",
    COFFEE: "/assets/Coffee.png",
    BATMAN: "/assets/batman.png",
    GOOFY: "/assets/goofy.png",
    ENGLISHMEN: "/assets/englishmen.jpg",
    INTRO1: "/assets/intro1.png",
    STEAL1: "/assets/steal1.png",
    PICKER: "/assets/picker.png",
    FACE: "/assets/face.png",
    HACK: "/assets/hack.png",
    ROADMAP: "/assets/roadmap.png",
    HIRE: "/assets/hire.png",
  },
  PROJECTS: {
    IMG1: "/assets/1.svg",
    IMG2: "/assets/2.svg",
    IMG3: "/assets/3.svg",
    IMG4: "/assets/4.svg",
    P1_USER: "/assets/Projects/1/user.png",
    P1_DASH_USER: "/assets/Projects/1/dashboard_user.png",
    P1_DASH_TWEET: "/assets/Projects/1/dashboard_tweet.png",
    P2_LANDING: "/assets/Projects/2/landing page.png",
    P3_LANDING: "/assets/Projects/3/landing page.png",
    P3_REGISTER: "/assets/Projects/3/register.png",
    P4_LANDING: "/assets/Projects/4/landing page.png",
    P4_QUOTE: "/assets/Projects/4/quote.png",
    CAMERA_MAN: "/assets/camera_man.png",
  }
};
